<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $data['type'] }} Report</title>
    <style>
        body { font-family: 'Courier New', Courier, monospace; font-size: 12px; margin: 0; padding: 10px; background: #fff; color: #000; }
        .receipt { max-width: 300px; margin: 0 auto; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .fw-bold { font-weight: bold; }
        .line { border-bottom: 1px dashed #000; margin: 5px 0; }
        .row { display: flex; justify-content: space-between; }
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>

    <div class="receipt">
        <div class="text-center fw-bold">
            {{ $data['store_name'] ?? 'Sari-Sari Store' }}<br>
            TIN: {{ $data['tin'] ?? '000-000-000' }}<br>
            MIN: {{ $data['machine_no'] }}
        </div>

        <div class="text-center" style="margin-top: 10px; font-size: 14px;">
            ** {{ $data['type'] }} **
        </div>
        <div class="text-center">{{ $data['date'] }}</div>

        <div class="line"></div>

        <div class="row"><span>Beg OR No:</span> <span>{{ $data['beg_or'] }}</span></div>
        <div class="row"><span>End OR No:</span> <span>{{ $data['end_or'] }}</span></div>
        
        <div class="row"><span>Trans Count:</span> <span>{{ $data['trans_count'] }}</span></div>

        <div class="line"></div>

        <div class="fw-bold">SALES SUMMARY</div>
        <div class="row"><span>Gross Sales:</span> <span>{{ number_format($data['total_sales'], 2) }}</span></div>
        <div class="row"><span>Cash Sales:</span> <span>{{ number_format($data['cash_sales'], 2) }}</span></div>
        <div class="row"><span>Card/Digi:</span> <span>{{ number_format($data['card_sales'], 2) }}</span></div>
        <div class="row"><span>Credit:</span> <span>{{ number_format($data['credit_sales'], 2) }}</span></div>

        <div class="line"></div>

        <div class="fw-bold">TAX BREAKDOWN</div>
        <div class="row"><span>Vatable Sales:</span> <span>{{ number_format($data['vatable_sales'], 2) }}</span></div>
        <div class="row"><span>VAT Amount (12%):</span> <span>{{ number_format($data['vat_amount'], 2) }}</span></div>
        <div class="row"><span>VAT Exempt:</span> <span>{{ number_format($data['vat_exempt'], 2) }}</span></div>
        <div class="row"><span>Zero Rated:</span> <span>0.00</span></div>

        <div class="line"></div>

        <div class="fw-bold">ACCUMULATORS</div>
        <div class="row"><span>Old Grand Total:</span> <span>{{ number_format($data['old_accumulated_sales'], 2) }}</span></div>
        <div class="row"><span>Today's Sales:</span> <span>{{ number_format($data['total_sales'], 2) }}</span></div>
        <div class="line"></div>
        <div class="row fw-bold"><span>NEW GRAND TOTAL:</span> <span>{{ number_format($data['new_accumulated_sales'], 2) }}</span></div>

        <div class="text-center" style="margin-top: 20px;">
            <div>Report Generated By: System</div>
            <div>--- End of Report ---</div>
        </div>

        <button onclick="window.print()" class="no-print" style="width: 100%; padding: 10px; margin-top: 20px; background: #000; color: #fff; border: none; cursor: pointer;">PRINT REPORT</button>
    </div>

</body>
</html>